version: '3'

valumes:
  prometheus_data:
    name: prometheus_data
    driver: local

  grafana_data:
    name: grafana_data
    driver: local

networks:
  monitoring:
    name: monitoring

services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - 'prometheus_data:/prometheus'
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    ports:
      - 9090:9090
